import = ["~/.config/alacritty/themes/dracula.toml"]

[shell]
program = "/usr/bin/fish"

[font]
size = 12.0

[font.normal]
family = "Iosevka Extended"

[window]
dynamic_title = false
dynamic_padding = true

[scrolling]
history=1000
