
add_newline=true

[line_break]
disabled = true

[character]
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'

[directory]
truncation_length=1
home_symbol=''

[battery]
disabled=true

[cmd_duration]
disabled=true

[username]
style_user="bold #87CEEB"
show_always=false

[python]
symbol="\ue235 "
pyenv_version_name = true
format='via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[cmake]
disabled=true
