require("packer").startup(function()
	use("wbthomason/packer.nvim")
    use("lewis6991/impatient.nvim")
	use("dracula/vim")
	use("ycm-core/YouCompleteMe")
    use("numToStr/Comment.nvim")
    use("kyazdani42/nvim-web-devicons")
	use("nvim-lualine/lualine.nvim")
	use("romgrk/barbar.nvim")
	use("nvim-lua/plenary.nvim")
	use("nvim-tree/nvim-tree.lua")
	use({ "akinsho/toggleterm.nvim", tag = "*" })
	use({"nvim-treesitter/nvim-treesitter", run=":TSUpdate"})
end)
